export const SUPPORTED_LANGUAGES = {
  en: {
    equalsLabel: "Equals",
    doesntEqualLabel: "Does not equal",
    greaterThanLabel: "Greater than",
    greaterOrEqualThanLabel: "Greater than or equal",
    lessThanLabel: "Less than",
    lessOrEqualThanLabel: "Less than or equal",
    containsLabel: "Contains",
    doesntContainsLabel: "Does not contain",
    startsWithLabel: "Starts with",
    doesntStartWithLabel: "Does not start with",
    trueLabel: "True",
    falseLabel: "False",
    fieldInputLabel: "Field",
    fieldInputPlaceHolder: "Choose a field",
    operatorInputLabel: "Operator",
    operatorInputPlaceHolder: "Choose an operator",
    valueInputLabel: "Value",
    addRuleBtnLabel: "Add",
    resetBtnLabel: "Reset",
    searchBtnLabel: "Search",
    filterLogicInputLabel: "Choose the filter logic",
    andOperatorLabel: "AND",
    orOperatorLabel: "OR",
    customLogicLabel: "CUSTOM",
    customLogicInputLabel: "Custom logic",
    customLogicHelpText: "Use parentheses, AND, OR to customize the logic. e.g. : (1 AND 2 AND 3) OR 4",
    wrongCustomLogicErrorMsg: "Wrong custom logic !",
    wrongCustomLogicNumbersErrorMsg: "Please use the numbers corresponding to the added filters !",
    unusedFilterRulesInCustomLogicErrorMsg:
      "Some filters are not used, please use them or delete them before trying again !"
  },
  fr: {
    equalsLabel: "Égale à",
    doesntEqualLabel: "N'est pas égale à",
    greaterThanLabel: "Supérieur à",
    greaterOrEqualThanLabel: "Supérieur ou égale à",
    lessThanLabel: "Inférieur à",
    lessOrEqualThanLabel: "Inférieur ou Égale à",
    containsLabel: "Contient",
    doesntContainsLabel: "Ne contient pas",
    startsWithLabel: "Commence par",
    doesntStartWithLabel: "Ne commence pas par",
    trueLabel: "Vrai",
    falseLabel: "Faux",
    fieldInputLabel: "Champ",
    fieldInputPlaceHolder: "Choisissez un champ",
    operatorInputLabel: "Opérateur",
    operatorInputPlaceHolder: "Choisissez un opérateur",
    valueInputLabel: "Valeur",
    addRuleBtnLabel: "Ajouter",
    resetBtnLabel: "Réinitialiser",
    searchBtnLabel: "Rechercher",
    filterLogicInputLabel: "Choisissez la logique du filtre",
    andOperatorLabel: "ET",
    orOperatorLabel: "OU",
    customLogicLabel: "PERSONNALISÉE",
    customLogicInputLabel: "Logique personnalisée",
    customLogicHelpText:
      "Utilisez les parenthèses, ET, OU  pour personnaliser la logique. par exemple : (1 AND 2 AND 3) OR 4",
    wrongCustomLogicErrorMsg: "Logique personnalisée erronée !",
    wrongCustomLogicNumbersErrorMsg: "Veuillez utiliser les nombres correspondants aux filtres ajoutés !",
    unusedFilterRulesInCustomLogicErrorMsg:
      "Certains filtres ne sont pas utilisés, veuillez les utiliser ou les supprimer avant de réessayer !"
  }
};
